"use client";
import React from 'react';
import { AppShell, MantineProvider } from '@mantine/core';
import Sidebar from '@/components/dashboard/Sidebar';
import Navbar from '@/components/dashboard/Navbar';
// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <MantineProvider>
            <AppShell
                padding="md"
                navbar={{ 
                    width: 250, 
                    breakpoint: 'sm',
                    collapsed: { mobile: false }
                }}
                header={{ 
                    height: 60 
                }}
                styles={(theme) => ({
                    main: {
                        backgroundColor: theme.colors.gray[0],
                    },
                })}
            >
                <AppShell.Navbar><Sidebar /></AppShell.Navbar>
                <AppShell.Header><Navbar /></AppShell.Header>
                {children}
            </AppShell>
        </MantineProvider>
    )
}